### PR TITLE
Use path.join for cross-platform file save.

### PR DESCRIPTION
**Pull request by nebeker**
Just like we talked about earlier. Give it a try.

### CODE REVIEW

**Comment by skluttrell** [comment]
I guess I was working on this at the same time you were last night. Take a look at what I changed already and let me know if you concur.

**Comment by nebeker** [comment]
Your branch looks good, but you don't need to check for Windows. Also, don't hardcode "Documents," use [platform-folders](https://www.npmjs.com/package/platform-folders)' `getPath('documents')` instead.

**Comment by skluttrell** [comment]
Couldn't figure out platform_folders so I used the app function instead.

**Comment by nebeker** [comment]
I suppose that'll work too.

**Comment by skluttrell** [comment]
I'll close this merge request with what we have then if that's cool.

**Comment by nebeker** [comment]
Yup. I tested it and it works great!

**Pull request closed without merging**
